import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/raw';
import { z } from 'zod';
export const dynamic='force-dynamic';
const date=z.string().refine(x=>x===''||(/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x));
const stamp=z.string().refine(x=>x===''||!Number.isNaN(Date.parse(x)));
const task=z.object({id:z.string().uuid(),title:z.string().trim().min(1).max(240),area:z.enum(['Personal','Trabajo','Estudio','Iglesia','Proyectos']),project:z.string().max(120),notes:z.string().max(10000),priority:z.number().int().min(1).max(3),minutes:z.number().int().min(5).max(1440),status:z.enum(['inbox','todo','doing','waiting','done']),planDate:date,deadline:date,followUp:date,top:z.boolean(),created:stamp,updated:stamp,completed:stamp});
const data=z.object({tasks:z.array(task).max(2000),budgets:z.record(z.string().regex(/^\d{4}-\d{2}-\d{2}$/),z.number().int().min(0).max(1440))}).superRefine((d,c)=>{const ids=new Set<string>();const tops:Record<string,number>={};for(const t of d.tasks){if(ids.has(t.id))c.addIssue({code:'custom',message:'ID repetido'});ids.add(t.id);if(t.top){if(!t.planDate||t.status==='waiting')c.addIssue({code:'custom',message:'Top 3 requiere una fecha y una tarea disponible'});tops[t.planDate]=(tops[t.planDate]||0)+1;}}if(Object.values(tops).some(n=>n>3))c.addIssue({code:'custom',message:'Elegí un máximo de 3 prioridades por día'});});
const reply=(x:unknown,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const u=await getChatGPTUser();if(!u)return reply({error:'Iniciá sesión para ver tus pendientes.'},401);try{const row=await database().prepare('SELECT data,version FROM workspaces WHERE owner=?').bind(u.userId).first<{data:string,version:number}>();return reply(row?{data:JSON.parse(row.data),version:row.version}:{data:{tasks:[],budgets:{}},version:0});}catch(e){console.error('Read state',e);return reply({error:'No pudimos cargar tus pendientes. Intentá nuevamente.'},503);}}
export async function PUT(req:Request){const u=await getChatGPTUser();if(!u)return reply({error:'Iniciá sesión para guardar.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Origen no permitido.'},403);try{const text=await req.text();if(text.length>2000000)return reply({error:'El espacio superó el tamaño permitido.'},413);let value;try{value=JSON.parse(text)}catch{return reply({error:'Formato inválido.'},400)}const parsed=z.object({data,version:z.number().int().min(0)}).safeParse(value);if(!parsed.success)return reply({error:parsed.error.issues[0]?.message||'Revisá los datos de la tarea.'},400);const db=database();const input=parsed.data;await db.prepare('INSERT OR IGNORE INTO workspaces (owner,data,version) VALUES (?,?,0)').bind(u.userId,JSON.stringify({tasks:[],budgets:{}})).run();const result=await db.prepare('UPDATE workspaces SET data=?,version=version+1 WHERE owner=? AND version=?').bind(JSON.stringify(input.data),u.userId,input.version).run();if(!result.meta.changes)return reply({error:'Hay cambios desde otro dispositivo. Actualizá la vista antes de volver a guardar.'},409);return reply({data:input.data,version:input.version+1});}catch(e){console.error('Save state',e);return reply({error:'No se guardaron los cambios. Tu edición sigue abierta; volvé a intentar.'},503);}}
