export type Task = { id: string; title: string; area: string; project: string; notes: string; priority: number; minutes: number; status: 'inbox'|'todo'|'doing'|'waiting'|'done'; planDate: string; deadline: string; followUp: string; top: boolean; updated: string; created: string; completed: string };
export type Data = { tasks: Task[]; budgets: Record<string,number> };
export const areas = ['Personal','Trabajo','Estudio','Iglesia','Proyectos'];
export const states: Record<Task['status'],string> = {inbox:'Sin organizar',todo:'Pendiente',doing:'En curso',waiting:'Esperando',done:'Completada'};
export function today() { return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
export function addDays(date:string,n:number) { const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10); }
export function dayLabel(date:string) { if(!date) return ''; return new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')); }
export function attention(t:Task,d:string) { return t.status!=='done' && (!!t.deadline&&t.deadline<d || !!t.followUp&&t.followUp<=d || !!t.planDate&&t.planDate<d); }
export function reason(t:Task,d:string) { if(t.deadline&&t.deadline<d)return 'Vencimiento pendiente';if(t.deadline===d)return 'Vence hoy';if(t.status==='doing')return 'Ya la empezaste';if(t.priority===3)return 'Prioridad alta';if(t.deadline&&t.deadline<=addDays(d,3))return 'Vence pronto';return t.minutes<=30?'Cabe en un bloque corto':'Avance en tus pendientes'; }
export function score(t:Task,d:string) { return (t.deadline&&t.deadline<d?1000:t.deadline===d?800:t.deadline&&t.deadline<=addDays(d,3)?400:0)+(t.status==='doing'?200:0)+t.priority*60+(t.planDate&&t.planDate<=d?40:0); }
export function suggestions(tasks:Task[],date:string,budget:number) { const planned=tasks.filter(t=>t.planDate===date&&t.status!=='waiting');let left=Math.max(0,budget-planned.reduce((s,t)=>s+t.minutes,0));let slots=Math.max(0,3-tasks.filter(t=>t.planDate===date&&t.top).length); const chosen:Task[]=[];const candidates=tasks.filter(t=>t.status!=='done'&&t.status!=='waiting'&&!(t.top&&t.planDate===date)&&(!t.planDate||t.planDate<=date)).sort((a,b)=>score(b,date)-score(a,date)||a.created.localeCompare(b.created));for(const t of candidates){const cost=t.planDate===date?0:t.minutes;if(slots&&cost<=left){chosen.push(t);left-=cost;slots--;}}return chosen; }
export function newTask(title=''):Task { const n=new Date().toISOString();return {id:crypto.randomUUID(),title,area:'Personal',project:'',notes:'',priority:2,minutes:30,status:'inbox',planDate:'',deadline:'',followUp:'',top:false,created:n,updated:n,completed:''}; }
